name: ml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - scipy
  - tensorflow
  - keras
  - pip
  - pip:
      - xgboost
      - lightgbm
      - catboost